### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by tomvanenckevort-ez** [EndzoneSoftware/UmbracoBase#4]
Would be good to go through the dependencies and get them upgraded to the latest Nuget versions as well. 
Especially RJP.MultiUrlPicker since it now has better ModelsBuilder support.
Nested Content package can be removed as well, since it now is built into Umbraco anyway.

**Comment by tomvanenckevort-ez** [comment]
When updating RJP.MultiUrlPicker, make sure to afterwards go to the Single Url Picker data type and change it to a Label, and then change it back to the Multi Url Picker. Otherwise the conversion to a single link will not happen.

**Comment by filipesousa** [comment]
All updated.
